apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: genazt-aws
  path: ./cluster/
  prune: true
  validation: client
