on:
  push:
    branches:
      - master
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - uses: actions/checkout@v1
      - name: Install CDK and typescript
        run: mkdir /home/runner/.npm-global && npm install typescript && npm install -g aws-cdk && cd cdk-k3s/ && npm install
        env:
          NPM_CONFIG_PREFIX: /home/runner/.npm-global
      - name: Show diff
        run: cd cdk-k3s/ && /home/runner/.npm-global/bin/cdk diff
        env:
          AWS_DEFAULT_REGION: 'eu-central-1'
          NPM_CONFIG_PREFIX: /home/runner/.npm-global
      - name: Deploy changes to AWS
        run: cd cdk-k3s/ && /home/runner/.npm-global/bin/cdk deploy --require-approval never
        env:
          AWS_DEFAULT_REGION: 'eu-central-1'
          NPM_CONFIG_PREFIX: /home/runner/.npm-global
